### PR TITLE
Change base image to CentOS and set user to non-root

### PR DESCRIPTION
**Pull request by anmolbabu**
tendrl-bug-id: fabric8-hdd/supervisor#30
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
Verification underway.
!!! Don't Merge !!!

**Comment by anmolbabu** [comment]
Associated container-index PR https://github.com/CentOS/container-index/pull/236

**Comment by anmolbabu** [comment]
| Error: EACCES: permission denied, scandir '/home/hdd-supervisor'
-- | --
  | TypeError: Cannot read property 'get' of undefined
  | at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
  | at /usr/lib/node_modules/npm/bin/npm-cli.js:83:20
  | at cb (/usr/lib/node_modules/npm/lib/npm.js:214:22)
  | at /usr/lib/node_modules/npm/lib/npm.js:252:24
  | at /usr/lib/node_modules/npm/lib/config/core.js:81:7
  | at Array.forEach (<anonymous>)
  | at /usr/lib/node_modules/npm/lib/config/core.js:80:13
  | at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
  | at /usr/lib/node_modules/npm/lib/config/core.js:110:20
  | at /usr/lib/node_modules/npm/lib/config/load-prefix.js:48:7
  | /usr/lib/node_modules/npm/lib/utils/error-handler.js:205
  | if (npm.config.get('json')) {
  | ^
  | TypeError: Cannot read property 'get' of undefined
  | at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
  | at emitOne (events.js:116:13)
  | at process.emit (events.js:211:7)
  | at process._fatalException (bootstrap_node.js:374:26)

**Comment by anmolbabu** [comment]
Trying with RUN npm config set unsafe-perm=true

**Comment by anmolbabu** [comment]
Verified to be working fine now

**Comment by anmolbabu** [comment]
This needs to be merged before https://github.com/CentOS/container-index/pull/236 can be merged.

**Comment by anmolbabu** [comment]
@mitchharpur @miteshvp @dev-gaur @mik-dass @mohammedzee1000 Please review

**Review by mohammedzee1000 — APPROVED** [review]
LGTM

**Comment by anmolbabu** [comment]
Merging based on ack from @mohammedzee1000

**Pull request merged**
