### PR TITLE
Adding linting support

### PR DESCRIPTION
**Pull request by devang-gaur**
I've chosen to go with eslint. Its highly configurable and customisable.

Targeting issue #4 .

### CODE REVIEW

**Comment by devang-gaur** [comment]
Hey @anmolbabu , I've shut PR #7. Merge this one ( targets #4 ).
I have the code ready fixed linting errors (fixes 
#11  ) . Will push them in a seperate PR after this gets merged.

**Comment by anmolbabu** [comment]
>Hey @anmolbabu , I've shut PR #7. Merge this one ( targets #4 ).

How is this relevant to #4 

>I have the code ready fixed linting errors (fixes
#11 ) . Will push them in a seperate PR after this gets merged.

I don't see the PR split yet..
Because I still see linting fixes in
1. tests/api_test.js
2. src/utils/util.js
3. src/api/validations.js
4. src/api/routes.js
5. src/api/handlers.js
6. main.js

Remove them from your commit using 
1. git reset HEAD^ <list of files>
2. git commit -s
3. git push ....

You can push those in a new commit that targets linter fixes i.e, https://github.com/fabric8-hdd/supervisor/issues/11

Rest looks good to me..
I can approve it
But lets get an ack from @miteshvp as well
With ack from @miteshvp I can merge..

**Comment by miteshvp** [comment]
@anmolbabu @dev-gaur @mik-dass - you don't need to wait for an acknowledgement. I feel you should go ahead and merge if it looks ok to you guys.

**Comment by devang-gaur** [comment]
Commit e192d2403dcfedf0bea4474f15365a3dc628c921 aims at #11 !

**Review by anmolbabu — APPROVED** [review]

**Pull request merged**
