### PR TITLE
Change references to docker local repos to registry.centos/registry.devshift

### PR DESCRIPTION
**Pull request by anmolbabu**
fabric8-hdd-bug-id: fabric8-hdd/supervisor#2
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
Please don't merge..
NOT YET VERIFIED

**Comment by anmolbabu** [comment]
@mitchharpur @miteshvp @mik-dass @dev-gaur Please review

**Comment by mik-dass** [comment]
LGTM

**Comment by anmolbabu** [comment]
Verified deploy script, changes in template and make file.
The remainder is just a move from docker hub to registry.devshift(They were previously verified for dockerhub) and can be verified on registry.devshift only with this PR merged and the PR on almighty jobs repo merged

**Comment by dev-gaur** [comment]
LGTM

**Review by devang-gaur — APPROVED** [review]
LGTM

**Pull request merged**
