### PR TITLE
Parameter-ise node version

### PR DESCRIPTION
**Pull request by anmolbabu**
Supply the nodejs version as arguement to docker build command
ex: docker build -t <image-name> --build-arg VERSION="5.6.0" .

fabric-hdd-bug: fabric8-hdd/supervisor#41
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by mik-dass** [comment]
LGTM

**Comment by mitchharpur** [comment]
Looks good.

**Comment by mitchharpur** [comment]
paramerise the port using current value as a default

**Review by mitchharpur — APPROVED** [review]
lets just ensure that port is parameterized too.

**Comment by anmolbabu** [comment]
@mitchharpur Ack I'll parameter-ise the port in a subsequent PR

**Pull request merged**
