### PR TITLE
Added linting support

### PR DESCRIPTION
**Pull request by devang-gaur**
I've chose to use eslint tool for linting purpose.

The tool is highly customisable and configurable. The .eslintrc.json file is the linter config file for the repo.

### CODE REVIEW

**Review by anmolbabu — CHANGES_REQUESTED** [review]
Are the changes(space replaced with tabs) in other files result of running eslint on the source?
Also Please add the linter cico script ..

**Comment by devang-gaur** [comment]
Yes, Anmol. Some linting errors are still present, they will be fixed automatically as the code matures.

I've added the cico script. Please check.

**Comment by anmolbabu** [comment]
ok then I would suggest you this:

1. Raise an issue on the repo to "Fix linter errors"
2. Split this PR into 2:
   a. one for just adding the linter tool + cico-linter script
   b. one for fixing the linter across all source files in the repo

Just for ease of reviewing

**Comment by devang-gaur** [comment]
alright

**Comment by devang-gaur** [comment]
Close this one!

**Pull request closed without merging**
