### PR TITLE
Removed unnecessary npm start execution

### PR DESCRIPTION
**Pull request by devang-gaur**
Fixes issue #13 & #3

### CODE REVIEW

**Review by anmolbabu — APPROVED** [review]

**Review by anmolbabu — COMMENTED** [review]
Remove it from Jenkinsfile also

**Comment by anmolbabu** [comment]
Also please link this PR against https://github.com/fabric8-hdd/supervisor/issues/3

**Comment by devang-gaur** [comment]
Done. Edited my earlier comment.

**Review by anmolbabu — CHANGES_REQUESTED** [review]
Can you make all changes that we had discussed like:
1. Removing entries from Makefile
2. Fixing Dockerfile.tests

**Comment by devang-gaur** [comment]
Alright

**Pull request closed without merging**
